[Version]
Class=IExpress
SEDVersion=3.0
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\PC\.gemini\antigravity\scratch\Setup-InvoiceScraper.exe
FriendlyName=Invoice Scraper Extension Auto-Installer
AppLaunched=cmd.exe /c Setup-InvoiceScraper.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
[SourceFiles]
SourceFiles0=C:\Users\PC\.gemini\antigravity\scratch\invoice-scraper-extension\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=
%FILE5%=
%FILE6%=
%FILE7%=
%FILE8%=
%FILE9%=
%FILE10%=
[Strings]
FILE0="manifest.json"
FILE1="content.js"
FILE2="background.js"
FILE3="popup.html"
FILE4="popup.js"
FILE5="popup.css"
FILE6="test-invoice.html"
FILE7="updates.xml"
FILE8="version.json"
FILE9="README.md"
FILE10="Setup-InvoiceScraper.bat"
